# print(1)
# raise ValueError("meri Marzi")
# # raise ValueError
# print(2)

try:
    num = 5/0
except:
    print("An error occured")
    raise